### ISSUE TITLE
Thank you & some ideas

### ISSUE THREAD

**Issue by C485** [kiredevsandhacks/PrettifyMyWebApi#2]
I've looked at your code, and it's clean, and i saw some //TODO :D 
I've some ideas that will make this addon perfect:
1. Add option to change state/status near Save hyperlink, just display 2 options that can be changed and that's all
2. Like you specified in code, add support for DateTime - i'll highly suggest using moment.js for that to avoid any problems
3. File field support - simple select file to update, also download file 
4. Add support for lookup fields, basic only like edit box that allows user to change logicalname/id - it will be difficult to create searchbox
5. impersonate - save as user
6. More that i can ask for - compare 2 records aka button next to Save hyperlink that will give me table of differences between records.
7. It would be great to basically remove second step (double click on addon), than just add "show/get raw json" next to Save hyperlink.

Also i want to thank you for this awesome addon! keep up the great work. Sadly i cannot contribute because i've my own project and already very limited free time.

**Comment by kiredevsandhacks** [comment]
Thanks for the suggestions and your kind words! I will consider each of them for my next update. 

As you said, some things will be hard to implement. I really like suggestion #7, never thought of that. The reason why I display the raw JSON first, is that I don't want to give the user that he is looking at some kind of official format, since I take the JSON string and modify it in my own format. But giving the option to display the raw value is a great idea! 

I also like the idea of #5: impersonation, will also add that when I got the time. Maybe I'll just start with a raw guid that a user can paste instead of building a custom lookup to systemusers. As you said, it will not be easy to build that.

**Comment by C485** [comment]
Sure, keep it simple, improvements can be done any time.

I don't want to spam you with issues on github so:
1. Improvement - Preview in lookups should move page to right, why? Make a simple test, click on Preview, in preview click another Preview, now 2nd preview will be created but off screen. BTW. that's actually GREAT feature, that i can "drill" down from one lookup.
2. Idea - For many records, add ability to expand/collapse records - i guess you can copy code for that from any other addons dedicated to json
3. Idea - Make links clickable - check metadata? check if http/https is present?
4. Bug - Open in Web Api hyperlink doesn't work in preview, it opens proper record id but wrong logicalname (gets it from root record), open in form works :D

**Comment by kiredevsandhacks** [comment]
Thanks for the suggestions! Keep em coming!

I really like the idea of scrolling right after hitting preview! Will implement it.

And thx for notifying me of the bug. At one time the preview pages maintained their own state, but it got buggy somewhere along the way I think. Will fix.

**Comment by C485** [comment]
your wish is my command :D

I had an idea of adding menu to each field with options to filter by these fields but... this is stupid, from this idea there is short path to actually rebuilding advanced find :D i guess this addon is not for this

Small and easy idea to implement - add small header to preview to indicate that it's actually a preview of record, maybe change background a little bit.

another idea is to add "html preview" - an eye icon or something, to any single/multiple lines text field - sometimes these is some html in them, it would be great to have a small 'preview' window with content of that field rendered. It may be dangerous because you'll render content in same tab, and this can break css etc. so i guess needs to be iframe :/

i heavily use you addon already so be prepared to receive issues :D

**Comment by kiredevsandhacks** [comment]
So happy that you like the extension :). Keep the suggestions coming!

About rendering the html, yes, that is very dangerous. I don't want extension users to get xss'ed. I guess I could render it in a sandboxed iframe. Or maybe I could use DOMPurify. Will have to research this, it is tricky to get right and easy to do wrong.

About the preview header, that's also a valid point. I already received complaints that the 'x' button in the top right is easy to miss. I might change it into a proper button saying 'Close Preview' or something to make it clear what the context is.

**Comment by kiredevsandhacks** [comment]
I implemented some of your ideas and fixed some bugs. Along with some other stuff. There is more I want to implement later but I don't want to change too much stuff in one go as to not break things too much if there are bugs. The package is currently pending in the chrome store. Should be approved after within a few days.  Please feel free to let me know if there are any issues!

Changes:
- preview will now display as a table
- open record in web api bug fixed for previewed records
- scrolling to the right after preview
- close preview button added instead of the x
- copy to clipboard functionality added
- nested values are now rendering properly

For later:
- clicking once instead of twice with the option to view the raw json
- impersonating users
- editing date fields
- editing lookup fields
- editing state/status. Will need to be a seperate menu as Dynamics does not always allow this if you edit them in one go with other fields
- multi select optionsets

Might implement:
- file field support (upload + download)
- making links clickable
- previewing html in a sandboxed iframe

**Comment by C485** [comment]
Thanks! I just realized that money fields cannot be edited, i don't remember if they're editable in ver 1.0

//edit: other features work without problems, great job!

**Comment by kiredevsandhacks** [comment]
That's a good one, I forgot about Money fields. Will add to the todo list.

Thanks for testing! Good to hear everything is working properly.

**Comment by kiredevsandhacks** [comment]
Version 1.0.2 is now pending in the Chrome store! Includes the following updates:
- Money fields can now be updated
- Impersonate other users when updating a record
- Editing lookups is now supported
- Some small styling fixes and bugfixes.

For later:

- clicking once instead of twice with the option to view the raw json
- editing date fields
- editing state/status.
- multi select optionsets

Might implement:

- file field support (upload + download)
- making links clickable
- previewing html in a sandboxed iframe
